### ISSUE TITLE
Change domain name

### ISSUE THREAD

**Issue by Smolevich** [ridi/traefik#4]
I have a problem with reconfuring certificates.
in begin i create ssl certificates by `mkcert` for domain local.ridi.io, but if can change domain on `local.custom_name.io`, delete old certificates and regenerate docker-compose configuration with new domain , all requests failes with error `DNS_PROBE_FINISHED_NXDOMAIN`. 
Do you have same problem?

**Comment by imkitae** [comment]
I think you missed to update the dns resolver. Could you replace `local.ridi.io` to `local.custom_name.io` in Makefile, and run `sudo make dns-resolver` again?

**Comment by Smolevich** [comment]
This step was executed also, but on my sense old domain was cached in some file, but i can't understand where.

**Comment by imkitae** [comment]
By the way.. can I ask why you want to use this project? This is for internal use in our company. I recommend to use something other for your own local development.
